server.port=${port:8761}
spring.application.name=Discovery

service.registration.network=http://localhost:${server.port}/eureka/
eureka.client.service-url.defaultZone=${service.registration.network}

eureka.client.registerWithEureka=false
eureka.client.fetchRegistry=false
eureka.client.jersey.enabled=false

# eureka.client.enabled=false