server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/project/config-repo
        repos:
          development:
            pattern:
              - '*/development'
              - '*/staging'
            uri: https://github.com/development/config-repo
          staging:
            pattern:
              - '*/qa'
              - '*/production'
            uri: https://github.com/staging/config-repo